### ISSUE TITLE
Replacement gets confused with lots of small words

### ISSUE THREAD

**Issue by wyze** [lagden/highlight#1]
Here is a contrived example of what I mean:

```js
const source = 'A system for offer based restaurant reservations comprises a processor and a memory. The processor is configured to: receive a request for a reservation including a set of attributes such as a date or date range, a time range, a location, a cuisine, and a party size; determine a set of available reservations based on an actual table availability for the date, time, and the party size; determine one or more offers based on the date, time, and the party size; determine an overlapping subset between the set of available reservations and the one or more offers; and provide an indication of the overlapping subset. The memory is coupled to the processor and is configured to provide the processor with instructions.'
const q = 'are to a is in on the of at or an'
const highlighted = highlight(source, q)
```

This would produce the following and set to `highlighted` above:

<pre>
<b>the</b>0 system f<b>or</b> <b>of</b>fer b<b>the</b>1sed rest<b>the</b>1ur<b>an</b>t reserv<b>at</b>i<b>on</b>s compr<b>is</b>es <b>the</b>1 process<b>or</b> <b>an</b>d <b>the</b>1 mem<b>or</b>y. <b>The</b> process<b>or</b> <b>is</b> c<b>on</b>figured <b>to</b>: receive <b>the</b>1 request f<b>or</b> <b>the</b>1 reserv<b>at</b>i<b>on</b> <b>in</b>clud<b>in</b>g <b>the</b>1 set <b>of</b> <b>at</b>tributes such <b>the</b>1s <b>the</b>1 d<b>at</b>e <b>or</b> d<b>at</b>e r<b>an</b>ge, <b>the</b>1 time r<b>an</b>ge, <b>the</b>1 loc<b>at</b>i<b>on</b>, <b>the</b>1 cu<b>is</b><b>in</b>e, <b>an</b>d <b>the</b>1 p<b>the</b>1rty size; determ<b>in</b>e <b>the</b>1 set <b>of</b> <b>the</b>1v<b>the</b>1il<b>the</b>1ble reserv<b>at</b>i<b>on</b>s b<b>the</b>1sed <b>on</b> <b>an</b> <b>the</b>1ctu<b>the</b>1l t<b>the</b>1ble <b>the</b>1v<b>the</b>1il<b>the</b>1bility f<b>or</b> <b>the</b> d<b>at</b>e, time, <b>an</b>d <b>the</b> p<b>the</b>1rty size; determ<b>in</b>e <b>on</b>e <b>or</b> m<b>or</b>e <b>of</b>fers b<b>the</b>1sed <b>on</b> <b>the</b> d<b>at</b>e, time, <b>an</b>d <b>the</b> p<b>the</b>1rty size; determ<b>in</b>e <b>an</b> overl<b>the</b>1pp<b>in</b>g subset between <b>the</b> set <b>of</b> <b>the</b>1v<b>the</b>1il<b>the</b>1ble reserv<b>at</b>i<b>on</b>s <b>an</b>d <b>the</b> <b>on</b>e <b>or</b> m<b>or</b>e <b>of</b>fers; <b>an</b>d provide <b>an</b> <b>in</b>dic<b>at</b>i<b>on</b> <b>of</b> <b>the</b> overl<b>the</b>1pp<b>in</b>g subset. <b>The</b> mem<b>or</b>y <b>is</b> coupled <b>to</b> <b>the</b> process<b>or</b> <b>an</b>d <b>is</b> c<b>on</b>figured <b>to</b> provide <b>the</b> process<b>or</b> with <b>in</b>structi<b>on</b>s.
</pre>

-----------

I ran into this in my project at work where a user could potentially paste in a large body of text that is split and then attempts to highlight. I do have a fix and will submit a PR shortly.

**Comment by wyze** [comment]
Sorry to bother, but after writing a test, it looks like it is some other processing of the results that I am doing that is causing the weird output.

**Comment by lagden** [comment]
I am working on it...

**Comment by wyze** [comment]
Well, I can't reproduce it in a test, but when ran within my project, even without my extra processing, it still produces the output described above.

I'll submit my PR anyways and you can take a look.
